version: 2.1

jobs:
  build:
    docker:
      # - image: circleci/openjdk:8u242-jdk
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run:
          # 确定哪些目录已经更改，这里只统计子项目也就是project-dirs中包含的项目
          name: Determine which directories have changed
          command: |
            git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f1 | sort -u >  projects
            printf "Modified directories:\n"
            cat projects
            while read project; do
              if grep -Fxq $project project-dirs; then
                printf "\nTriggerring build for project: "$project
                curl -s -u ${CIRCLE_TOKEN}: -d build_parameters[CIRCLE_JOB]=${project} https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              fi
            done < projects
  demo-a-test:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    working_directory: ~/boot-demos/demo-a-test
    steps:
      - build-service:
          service-name: "demo-a-test"
  demo-redis:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    working_directory: ~/boot-demos/demo-redis
    steps:
      - build-service:
          service-name: "demo-redis"

commands:
  build-service:
    description: "Build a service and push image to dockerhub"
    parameters:
      service-name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/boot-demos

      - setup_remote_docker

      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

      # Download and cache dependencies,省的以后构建重复下载拖慢速度
      - restore_cache:
          keys:
            - << parameters.service-name >>-{{ checksum "pom.xml"}}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: << parameters.service-name >>-{{ checksum "pom.xml"}}

      # package into a jar and build image
      - run: mvn clean package -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI -Ddockerfile.maven.settings.auth=false

      # push docker image to docker hub
      - run: mvn dockerfile:push -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI

      # store raw content of src code
      - store_artifacts:
          path: target/classes
          destination: circle-ci-<< parameters.service-name >>