server:
  port: 8081

#oss:
#  enabled: true
#  type: MINIO
#  endpoint: http://192.168.1.5:9000  # 必须加 http 前缀，不能直接写ip
#  bucket: demo
#  access-key: DImVv5gxX4jCMtRjd9cA
#  secret-key: w1FbFj1E3xOtMxF3vpV9XXnMVzJvznepoaYkxF7S
#  region: tianjin

#oss:
#  enabled: true
#  type: ALIYUN
#  endpoint: https://oss-cn-beijing.aliyuncs.com
#  bucket: demo
#  accessKey: xxxxxxxxxxxx
#  secretKey: xxxxxxxxxxxx
#  region: https://oss-cn-beijing.aliyuncs.com # 对应阿里云区域

oss:
  enabled: true
  type: AMAZON_S3
  endpoint: https://s3.ap-southeast-1.amazonaws.com
  bucket: demo
  accessKey: xxxxxxxxxxxxxxxxx
  secretKey: xxxxxxxxxxxxxxxxx
  region: ap-southeast-1